steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/metatrader5:latest', '.']
images:
  - 'gcr.io/$PROJECT_ID/metatrader5:latest'
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET  # Set this for using a user-owned bucket for logs.
